# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid32"
  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  config.hiera.config_path = './configuration'
  config.hiera.config_file = 'hiera.yaml'
  config.hiera.data_path = './configuration'

  config.puppetconf.updates = {'main/environment' => 'test'}

  config.vbguest.auto_update = true

  # do NOT download the iso file from a webserver
  config.vbguest.no_remote = false


  config.vm.provision :puppet do |puppet|
    puppet.module_path = "./modules"
    puppet.manifests_path = "./manifests"
    puppet.manifest_file  = "base.pp"
  end

end
